In [6]:
import pandas as pd
df=pd.read_csv('Fact_table.csv')
df

,Date,year,month,day,DayOfWeek,UniqueCarrier,FlightNum,TailNum,Origin,Dest,...,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Delay_sum,ActualElapsedTime,Expected_ElapsedTime,AirTime,TaxiIn,TaxiOut
0,1/3/2008,2008,1,3,4,WN,335,N712SW,IAD,TPA,...,0,0,0,0,0,128,150,116,4,8
1,1/3/2008,2008,1,3,4,WN,3231,N772SW,IAD,TPA,...,0,0,0,0,0,128,145,113,5,10
2,1/3/2008,2008,1,3,4,WN,448,N428WN,IND,BWI,...,0,0,0,0,0,96,90,76,3,17
3,1/3/2008,2008,1,3,4,WN,3920,N464WN,IND,BWI,...,0,0,0,32,34,90,90,77,3,10
4,1/3/2008,2008,1,3,4,WN,378,N726SW,IND,JAX,...,0,0,0,0,0,101,115,87,4,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,6/12/2008,2008,6,12,4,AA,1865,N578AA,DFW,BUR,...,0,12,0,0,24,197,185,179,3,15
1048571,6/13/2008,2008,6,13,5,AA,1865,N465AA,DFW,BUR,...,0,5,0,35,41,190,185,176,4,10
1048572,6/14/2008,2008,6,14,6,AA,1865,N207AA,DFW,BUR,...,0,9,0,37,46,194,185,166,4,24
1048573,6/15/2008,2008,6,15,7,AA,1865,N455AA,DFW,BUR,...,0,32,0,76,115,217,185,173,3,41
1048574,6/17/2008,2008,6,17,2,AA,1865,N514AA,DFW,BUR,...,93,4,0,0,97,189,185,166,4,19

In [10]:
# df['Date']=pd.to_datetime(df['Date'])
df

,Date,year,month,day,DayOfWeek,UniqueCarrier,FlightNum,TailNum,Origin,Dest,...,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Delay_sum,ActualElapsedTime,Expected_ElapsedTime,AirTime,TaxiIn,TaxiOut
0,2008-01-03,2008,1,3,4,WN,335,N712SW,IAD,TPA,...,0,0,0,0,0,128,150,116,4,8
1,2008-01-03,2008,1,3,4,WN,3231,N772SW,IAD,TPA,...,0,0,0,0,0,128,145,113,5,10
2,2008-01-03,2008,1,3,4,WN,448,N428WN,IND,BWI,...,0,0,0,0,0,96,90,76,3,17
3,2008-01-03,2008,1,3,4,WN,3920,N464WN,IND,BWI,...,0,0,0,32,34,90,90,77,3,10
4,2008-01-03,2008,1,3,4,WN,378,N726SW,IND,JAX,...,0,0,0,0,0,101,115,87,4,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2008-06-12,2008,6,12,4,AA,1865,N578AA,DFW,BUR,...,0,12,0,0,24,197,185,179,3,15
1048571,2008-06-13,2008,6,13,5,AA,1865,N465AA,DFW,BUR,...,0,5,0,35,41,190,185,176,4,10
1048572,2008-06-14,2008,6,14,6,AA,1865,N207AA,DFW,BUR,...,0,9,0,37,46,194,185,166,4,24
1048573,2008-06-15,2008,6,15,7,AA,1865,N455AA,DFW,BUR,...,0,32,0,76,115,217,185,173,3,41
1048574,2008-06-17,2008,6,17,2,AA,1865,N514AA,DFW,BUR,...,93,4,0,0,97,189,185,166,4,19

In [ ]:
date_dim=pd.read_csv('Dim_Date.csv')
date_dim=date_dim.rename(columns={'FullDate':'Date'})
date_dim

,Date,DateKey,Year,Month,Day,Quarter,DayName,MonthName,DayOfWeek,IsWeekend,WeekOfYear
0,2008-01-01,20080101,2008,1,1,1,Tuesday,January,1,0,1
1,2008-01-02,20080102,2008,1,2,1,Wednesday,January,2,0,1
2,2008-01-03,20080103,2008,1,3,1,Thursday,January,3,0,1
3,2008-01-04,20080104,2008,1,4,1,Friday,January,4,0,1
4,2008-01-05,20080105,2008,1,5,1,Saturday,January,5,1,1
...,...,...,...,...,...,...,...,...,...,...,...
361,2008-12-27,20081227,2008,12,27,4,Saturday,December,5,1,52
362,2008-12-28,20081228,2008,12,28,4,Sunday,December,6,1,52
363,2008-12-29,20081229,2008,12,29,4,Monday,December,0,0,1
364,2008-12-30,20081230,2008,12,30,4,Tuesday,December,1,0,1
365,2008-12-31,20081231,2008,12,31,4,Wednesday,December,2,0,1

In [15]:
date_dim['Date']=pd.to_datetime(date_dim['Date'])

In [16]:
df=df.merge(date_dim,on='Date',how='left')

In [ ]:
del date_dim
dell=['year','month','day','DayOfWeek_x','Year','Month','Day','Quarter','DayName','MonthName','DayOfWeek_y','IsWeekend','WeekOfYear'] 
df=df.drop(columns=dell)

In [27]:
df

,UniqueCarrier,FlightNum,TailNum,Origin,Dest,Distance,Scheduled_DepTime,Actual_DepTime,Departure_Delay,Scheduled_ArrTime,...,NASDelay,SecurityDelay,LateAircraftDelay,Delay_sum,ActualElapsedTime,Expected_ElapsedTime,AirTime,TaxiIn,TaxiOut,DateKey
0,WN,335,N712SW,IAD,TPA,810,19:55:00,20:03:00,8,22:25:00,...,0,0,0,0,128,150,116,4,8,20080103
1,WN,3231,N772SW,IAD,TPA,810,7:35:00,7:54:00,19,10:00:00,...,0,0,0,0,128,145,113,5,10,20080103
2,WN,448,N428WN,IND,BWI,515,6:20:00,6:28:00,8,7:50:00,...,0,0,0,0,96,90,76,3,17,20080103
3,WN,3920,N464WN,IND,BWI,515,17:55:00,18:29:00,34,19:25:00,...,0,0,32,34,90,90,77,3,10,20080103
4,WN,378,N726SW,IND,JAX,688,19:15:00,19:40:00,25,21:10:00,...,0,0,0,0,101,115,87,4,10,20080103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,AA,1865,N578AA,DFW,BUR,1231,19:15:00,19:27:00,12,20:20:00,...,12,0,0,24,197,185,179,3,15,20080612
1048571,AA,1865,N465AA,DFW,BUR,1231,19:15:00,19:51:00,36,20:20:00,...,5,0,35,41,190,185,176,4,10,20080613
1048572,AA,1865,N207AA,DFW,BUR,1231,19:15:00,19:52:00,37,20:20:00,...,9,0,37,46,194,185,166,4,24,20080614
1048573,AA,1865,N455AA,DFW,BUR,1231,19:15:00,20:38:00,83,20:20:00,...,32,0,76,115,217,185,173,3,41,20080615
1048574,AA,1865,N514AA,DFW,BUR,1231,19:15:00,20:48:00,93,20:20:00,...,4,0,0,97,189,185,166,4,19,20080617

In [26]:
airport=pd.read_csv('Dim_Airport.csv')
airport

,airport_FK,Code,Airport Name,City
0,1,IAD,Washington Dulles International,"Washington, D.C. / Dulles"
1,2,IND,Indianapolis International,"Indianapolis, IN"
2,3,ISP,Long Island MacArthur,"Islip, NY"
3,4,JAN,Jackson–Medgar Wiley Evers International,"Jackson, MS"
4,5,JAX,Jacksonville International,"Jacksonville, FL"
...,...,...,...,...
293,294,WYS,Yellowstone,"West Yellowstone, MT"
294,295,BJI,Bemidji Regional,"Bemidji, MN"
295,296,INL,Falls International,"International Falls, MN"
296,297,Sources,NaN,NaN
297,298,http://mars.gmu.edu/jspui/bitstream/handle/192...,NaN,NaN

In [28]:
# لنفترض أن الجدول الأول فيه 'Date' والثاني فيه 'FullDate'
df = df.merge(airport, left_on='Origin', right_on='Code', how='left')

In [42]:
df = df.merge(airport, left_on='Dest', right_on='Code', how='left')

In [ ]:
# pd.options.display.max_columns = None

del airport
dele=['Airport Name_x','Airport Name_y']
df=df.drop(columns=dele)
df

In [2]:
import pandas as pd 
aircraft=pd.read_csv('Dim_Aircraft.csv')
aircraft

     TailNum Manufacturer     Model  YearMfr    Body_Type       Age_Category
0     N712SW       BOEING  B737-700   2006.0  Narrow-Body      New (0–5 yrs)
1     N772SW       BOEING  B737-800   2004.0  Narrow-Body      New (0–5 yrs)
2     N428WN       BOEING  B737-700   1999.0  Narrow-Body  Modern (6–15 yrs)
3     N464WN       BOEING  B737-800   1999.0  Narrow-Body  Modern (6–15 yrs)
4     N726SW       BOEING  B737-700   2007.0  Narrow-Body      New (0–5 yrs)
...      ...          ...       ...      ...          ...                ...
5037    N270      UNKNOWN   UNKNOWN      NaN      Unknown            Unknown
5038  N924WN       BOEING  B737-700   2003.0  Narrow-Body      New (0–5 yrs)
5039  N226UA       BOEING  B737-500   1998.0  Narrow-Body  Modern (6–15 yrs)
5040  N961UW       AIRBUS  A320-200   2012.0  Narrow-Body      New (0–5 yrs)
5041  N348AT       BOEING  B757-200   2004.0  Narrow-Body      New (0–5 yrs)

[5042 rows x 6 columns]

In [4]:
aircraft['Aircraft_FK']=range(1,len(aircraft)+1)
aircraft.to_csv('Dim_Aircraft.csv')

In [49]:
df = df.merge(aircraft, on='TailNum', how='left')
df

,UniqueCarrier,FlightNum,TailNum,Origin,Dest,Distance,Scheduled_DepTime,Actual_DepTime,Departure_Delay,Scheduled_ArrTime,Actual_ArrTime,Arrival_Delay,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Delay_sum,ActualElapsedTime,Expected_ElapsedTime,AirTime,TaxiIn,TaxiOut,DateKey,airport_FK_x,Airport Name_x,airport_FK_y,Airport Name_y,Manufacturer_x,Model_x,YearMfr_x,Body_Type_x,Age_Category_x,Manufacturer_y,Model_y,YearMfr_y,Body_Type_y,Age_Category_y,Aircraft_FK
0,WN,335,N712SW,IAD,TPA,810,19:55:00,20:03:00,8,22:25:00,22:11:00,-14,0,0,0,0,0,0,128,150,116,4,8,20080103,1,Washington Dulles International,40,Tampa International,BOEING,B737-700,2006.0,Narrow-Body,New (0–5 yrs),BOEING,B737-700,2006.0,Narrow-Body,New (0–5 yrs),1.0
1,WN,3231,N772SW,IAD,TPA,810,7:35:00,7:54:00,19,10:00:00,10:02:00,2,0,0,0,0,0,0,128,145,113,5,10,20080103,1,Washington Dulles International,40,Tampa International,BOEING,B737-800,2004.0,Narrow-Body,New (0–5 yrs),BOEING,B737-800,2004.0,Narrow-Body,New (0–5 yrs),2.0
2,WN,448,N428WN,IND,BWI,515,6:20:00,6:28:00,8,7:50:00,8:04:00,14,0,0,0,0,0,0,96,90,76,3,17,20080103,2,Indianapolis International,53,Baltimore/Washington International,BOEING,B737-700,1999.0,Narrow-Body,Modern (6–15 yrs),BOEING,B737-700,1999.0,Narrow-Body,Modern (6–15 yrs),3.0
3,WN,3920,N464WN,IND,BWI,515,17:55:00,18:29:00,34,19:25:00,19:59:00,34,2,0,0,0,32,34,90,90,77,3,10,20080103,2,Indianapolis International,53,Baltimore/Washington International,BOEING,B737-800,1999.0,Narrow-Body,Modern (6–15 yrs),BOEING,B737-800,1999.0,Narrow-Body,Modern (6–15 yrs),4.0
4,WN,378,N726SW,IND,JAX,688,19:15:00,19:40:00,25,21:10:00,21:21:00,11,0,0,0,0,0,0,101,115,87,4,10,20080103,2,Indianapolis International,5,Jacksonville International,BOEING,B737-700,2007.0,Narrow-Body,New (0–5 yrs),BOEING,B737-700,2007.0,Narrow-Body,New (0–5 yrs),5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,AA,1865,N578AA,DFW,BUR,1231,19:15:00,19:27:00,12,20:20:00,20:44:00,24,12,0,12,0,0,24,197,185,179,3,15,20080612,94,Dallas/Fort Worth International,52,Hollywood Burbank,BOEING,B737-800,2012.0,Narrow-Body,New (0–5 yrs),BOEING,B737-800,2012.0,Narrow-Body,New (0–5 yrs),3949.0
1048571,AA,1865,N465AA,DFW,BUR,1231,19:15:00,19:51:00,36,20:20:00,21:01:00,41,1,0,5,0,35,41,190,185,176,4,10,20080613,94,Dallas/Fort Worth International,52,Hollywood Burbank,BOEING,B777-200,2003.0,Wide-Body,New (0–5 yrs),BOEING,B777-200,2003.0,Wide-Body,New (0–5 yrs),3905.0
1048572,AA,1865,N207AA,DFW,BUR,1231,19:15:00,19:52:00,37,20:20:00,21:06:00,46,0,0,9,0,37,46,194,185,166,4,24,20080614,94,Dallas/Fort Worth International,52,Hollywood Burbank,AIRBUS,A320-200,2006.0,Narrow-Body,New (0–5 yrs),AIRBUS,A320-200,2006.0,Narrow-Body,New (0–5 yrs),4144.0
1048573,AA,1865,N455AA,DFW,BUR,1231,19:15:00,20:38:00,83,20:20:00,22:15:00,115,7,0,32,0,76,115,217,185,173,3,41,20080615,94,Dallas/Fort Worth International,52,Hollywood Burbank,BOEING,B777-200,2012.0,Wide-Body,New (0–5 yrs),BOEING,B777-200,2012.0,Wide-Body,New (0–5 yrs),4110.0
1048574,AA,1865,N514AA,DFW,BUR,1231,19:15:00,20:48:00,93,20:20:00,21:57:00,97,0,93,4,0,0,97,189,185,166,4,19,20080617,94,Dallas/Fort Worth International,52,Hollywood Burbank,BOEING,B757-200,2003.0,Narrow-Body,New (0–5 yrs),BOEING,B757-200,2003.0,Narrow-Body,New (0–5 yrs),3956.0

In [ ]:
del aircraft
dele=['Manufacturer_x','Model_x','YearMfr_x','Body_Type_x','Age_Category_x','Manufacturer_y','Model_y','YearMfr_y','Body_Type_y','Age_Category_y']
df=df.drop(columns=dele)

In [52]:
df

,UniqueCarrier,FlightNum,TailNum,Origin,Dest,Distance,Scheduled_DepTime,Actual_DepTime,Departure_Delay,Scheduled_ArrTime,Actual_ArrTime,Arrival_Delay,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Delay_sum,ActualElapsedTime,Expected_ElapsedTime,AirTime,TaxiIn,TaxiOut,DateKey,airport_FK_x,Airport Name_x,airport_FK_y,Airport Name_y,Aircraft_FK
0,WN,335,N712SW,IAD,TPA,810,19:55:00,20:03:00,8,22:25:00,22:11:00,-14,0,0,0,0,0,0,128,150,116,4,8,20080103,1,Washington Dulles International,40,Tampa International,1.0
1,WN,3231,N772SW,IAD,TPA,810,7:35:00,7:54:00,19,10:00:00,10:02:00,2,0,0,0,0,0,0,128,145,113,5,10,20080103,1,Washington Dulles International,40,Tampa International,2.0
2,WN,448,N428WN,IND,BWI,515,6:20:00,6:28:00,8,7:50:00,8:04:00,14,0,0,0,0,0,0,96,90,76,3,17,20080103,2,Indianapolis International,53,Baltimore/Washington International,3.0
3,WN,3920,N464WN,IND,BWI,515,17:55:00,18:29:00,34,19:25:00,19:59:00,34,2,0,0,0,32,34,90,90,77,3,10,20080103,2,Indianapolis International,53,Baltimore/Washington International,4.0
4,WN,378,N726SW,IND,JAX,688,19:15:00,19:40:00,25,21:10:00,21:21:00,11,0,0,0,0,0,0,101,115,87,4,10,20080103,2,Indianapolis International,5,Jacksonville International,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,AA,1865,N578AA,DFW,BUR,1231,19:15:00,19:27:00,12,20:20:00,20:44:00,24,12,0,12,0,0,24,197,185,179,3,15,20080612,94,Dallas/Fort Worth International,52,Hollywood Burbank,3949.0
1048571,AA,1865,N465AA,DFW,BUR,1231,19:15:00,19:51:00,36,20:20:00,21:01:00,41,1,0,5,0,35,41,190,185,176,4,10,20080613,94,Dallas/Fort Worth International,52,Hollywood Burbank,3905.0
1048572,AA,1865,N207AA,DFW,BUR,1231,19:15:00,19:52:00,37,20:20:00,21:06:00,46,0,0,9,0,37,46,194,185,166,4,24,20080614,94,Dallas/Fort Worth International,52,Hollywood Burbank,4144.0
1048573,AA,1865,N455AA,DFW,BUR,1231,19:15:00,20:38:00,83,20:20:00,22:15:00,115,7,0,32,0,76,115,217,185,173,3,41,20080615,94,Dallas/Fort Worth International,52,Hollywood Burbank,4110.0
1048574,AA,1865,N514AA,DFW,BUR,1231,19:15:00,20:48:00,93,20:20:00,21:57:00,97,0,93,4,0,0,97,189,185,166,4,19,20080617,94,Dallas/Fort Worth International,52,Hollywood Burbank,3956.0

In [53]:
route=pd.read_csv('Dim_Route.csv')
route

      route_FK Origin Dest  Distance
0            1    IAD  TPA       810
1            2    IND  BWI       515
2            3    IND  JAX       688
3            4    IND  LAS      1591
4            5    IND  MCO       828
...        ...    ...  ...       ...
5000      5001    MSP  BJI       199
5001      5002    MEM  COS       855
5002      5003    COS  MEM       855
5003      5004    BDL  MEM      1048
5004      5005    MEM  BDL      1048

[5005 rows x 4 columns]

In [54]:
df=df.merge(route,on=['Origin','Dest'],how='left')
df

,UniqueCarrier,FlightNum,TailNum,Origin,Dest,Distance_x,Scheduled_DepTime,Actual_DepTime,Departure_Delay,Scheduled_ArrTime,Actual_ArrTime,Arrival_Delay,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Delay_sum,ActualElapsedTime,Expected_ElapsedTime,AirTime,TaxiIn,TaxiOut,DateKey,airport_FK_x,Airport Name_x,airport_FK_y,Airport Name_y,Aircraft_FK,route_FK,Distance_y
0,WN,335,N712SW,IAD,TPA,810,19:55:00,20:03:00,8,22:25:00,22:11:00,-14,0,0,0,0,0,0,128,150,116,4,8,20080103,1,Washington Dulles International,40,Tampa International,1.0,1,810
1,WN,3231,N772SW,IAD,TPA,810,7:35:00,7:54:00,19,10:00:00,10:02:00,2,0,0,0,0,0,0,128,145,113,5,10,20080103,1,Washington Dulles International,40,Tampa International,2.0,1,810
2,WN,448,N428WN,IND,BWI,515,6:20:00,6:28:00,8,7:50:00,8:04:00,14,0,0,0,0,0,0,96,90,76,3,17,20080103,2,Indianapolis International,53,Baltimore/Washington International,3.0,2,515
3,WN,3920,N464WN,IND,BWI,515,17:55:00,18:29:00,34,19:25:00,19:59:00,34,2,0,0,0,32,34,90,90,77,3,10,20080103,2,Indianapolis International,53,Baltimore/Washington International,4.0,2,515
4,WN,378,N726SW,IND,JAX,688,19:15:00,19:40:00,25,21:10:00,21:21:00,11,0,0,0,0,0,0,101,115,87,4,10,20080103,2,Indianapolis International,5,Jacksonville International,5.0,3,688
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,AA,1865,N578AA,DFW,BUR,1231,19:15:00,19:27:00,12,20:20:00,20:44:00,24,12,0,12,0,0,24,197,185,179,3,15,20080612,94,Dallas/Fort Worth International,52,Hollywood Burbank,3949.0,4069,1231
1048571,AA,1865,N465AA,DFW,BUR,1231,19:15:00,19:51:00,36,20:20:00,21:01:00,41,1,0,5,0,35,41,190,185,176,4,10,20080613,94,Dallas/Fort Worth International,52,Hollywood Burbank,3905.0,4069,1231
1048572,AA,1865,N207AA,DFW,BUR,1231,19:15:00,19:52:00,37,20:20:00,21:06:00,46,0,0,9,0,37,46,194,185,166,4,24,20080614,94,Dallas/Fort Worth International,52,Hollywood Burbank,4144.0,4069,1231
1048573,AA,1865,N455AA,DFW,BUR,1231,19:15:00,20:38:00,83,20:20:00,22:15:00,115,7,0,32,0,76,115,217,185,173,3,41,20080615,94,Dallas/Fort Worth International,52,Hollywood Burbank,4110.0,4069,1231
1048574,AA,1865,N514AA,DFW,BUR,1231,19:15:00,20:48:00,93,20:20:00,21:57:00,97,0,93,4,0,0,97,189,185,166,4,19,20080617,94,Dallas/Fort Worth International,52,Hollywood Burbank,3956.0,4069,1231

In [ ]:
df.columns

del route

dellll=['Origin', 'Dest', 'Distance_x', 'Distance_y']
df=df.drop(columns=dellll)
df

,UniqueCarrier,FlightNum,TailNum,Scheduled_DepTime,Actual_DepTime,Departure_Delay,Scheduled_ArrTime,Actual_ArrTime,Arrival_Delay,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Delay_sum,ActualElapsedTime,Expected_ElapsedTime,AirTime,TaxiIn,TaxiOut,DateKey,airport_FK_x,Airport Name_x,airport_FK_y,Airport Name_y,Aircraft_FK,route_FK
0,WN,335,N712SW,19:55:00,20:03:00,8,22:25:00,22:11:00,-14,0,0,0,0,0,0,128,150,116,4,8,20080103,1,Washington Dulles International,40,Tampa International,1.0,1
1,WN,3231,N772SW,7:35:00,7:54:00,19,10:00:00,10:02:00,2,0,0,0,0,0,0,128,145,113,5,10,20080103,1,Washington Dulles International,40,Tampa International,2.0,1
2,WN,448,N428WN,6:20:00,6:28:00,8,7:50:00,8:04:00,14,0,0,0,0,0,0,96,90,76,3,17,20080103,2,Indianapolis International,53,Baltimore/Washington International,3.0,2
3,WN,3920,N464WN,17:55:00,18:29:00,34,19:25:00,19:59:00,34,2,0,0,0,32,34,90,90,77,3,10,20080103,2,Indianapolis International,53,Baltimore/Washington International,4.0,2
4,WN,378,N726SW,19:15:00,19:40:00,25,21:10:00,21:21:00,11,0,0,0,0,0,0,101,115,87,4,10,20080103,2,Indianapolis International,5,Jacksonville International,5.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,AA,1865,N578AA,19:15:00,19:27:00,12,20:20:00,20:44:00,24,12,0,12,0,0,24,197,185,179,3,15,20080612,94,Dallas/Fort Worth International,52,Hollywood Burbank,3949.0,4069
1048571,AA,1865,N465AA,19:15:00,19:51:00,36,20:20:00,21:01:00,41,1,0,5,0,35,41,190,185,176,4,10,20080613,94,Dallas/Fort Worth International,52,Hollywood Burbank,3905.0,4069
1048572,AA,1865,N207AA,19:15:00,19:52:00,37,20:20:00,21:06:00,46,0,0,9,0,37,46,194,185,166,4,24,20080614,94,Dallas/Fort Worth International,52,Hollywood Burbank,4144.0,4069
1048573,AA,1865,N455AA,19:15:00,20:38:00,83,20:20:00,22:15:00,115,7,0,32,0,76,115,217,185,173,3,41,20080615,94,Dallas/Fort Worth International,52,Hollywood Burbank,4110.0,4069
1048574,AA,1865,N514AA,19:15:00,20:48:00,93,20:20:00,21:57:00,97,0,93,4,0,0,97,189,185,166,4,19,20080617,94,Dallas/Fort Worth International,52,Hollywood Burbank,3956.0,4069

In [78]:
carrier_names = {
    "WN": "Southwest Airlines",
    "XE": "ExpressJet Airlines",
    "YV": "Mesa Airlines",
    "OH": "PSA Airlines",
    "OO": "SkyWest Airlines",
    "UA": "United Airlines",
    "US": "US Airways",
    "DL": "Delta Air Lines",
    "EV": "Atlantic Southeast Airlines",
    "F9": "Frontier Airlines",
    "FL": "AirTran Airways",
    "HA": "Hawaiian Airlines",
    "MQ": "American Eagle Airlines",
    "NW": "Northwest Airlines",
    "9E": "Pinnacle Airlines",
    "AA": "American Airlines",
    "AQ": "Aloha Airlines",
    "AS": "Alaska Airlines",
    "B6": "JetBlue Airways",
    "CO": "Continental Airlines"
}

Dim_carrier = pd.DataFrame(list(carrier_names.items()), columns=['CarrierCode', 'CarrierName'])

# إضافة Surrogate Key
Dim_carrier['CarrierKey'] = range(1, len(Dim_carrier) + 1)

In [81]:
Dim_carrier.to_csv("Dim_carrier.csv")

In [86]:
carr=pd.read_csv('Dim_Carrier.csv')
carr

    CarrierKey UniqueCarrier                  CarrierName
0            1            WN           Southwest Airlines
1            2            XE          ExpressJet Airlines
2            3            YV                Mesa Airlines
3            4            OH                 PSA Airlines
4            5            OO             SkyWest Airlines
5            6            UA              United Airlines
6            7            US                   US Airways
7            8            DL              Delta Air Lines
8            9            EV  Atlantic Southeast Airlines
9           10            F9            Frontier Airlines
10          11            FL              AirTran Airways
11          12            HA            Hawaiian Airlines
12          13            MQ      American Eagle Airlines
13          14            NW           Northwest Airlines
14          15            9E            Pinnacle Airlines
15          16            AA            American Airlines
16          17            AQ               Aloha Airlines
17          18            AS              Alaska Airlines
18          19            B6              JetBlue Airways
19          20            CO         Continental Airlines

In [87]:
df=df.merge(carr,on='UniqueCarrier',how='left')
df

,UniqueCarrier,FlightNum,TailNum,Scheduled_DepTime,Actual_DepTime,Departure_Delay,Scheduled_ArrTime,Actual_ArrTime,Arrival_Delay,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Delay_sum,ActualElapsedTime,Expected_ElapsedTime,AirTime,TaxiIn,TaxiOut,DateKey,airport_FK_x,Airport Name_x,airport_FK_y,Airport Name_y,Aircraft_FK,route_FK,CarrierKey,CarrierName
0,WN,335,N712SW,19:55:00,20:03:00,8,22:25:00,22:11:00,-14,0,0,0,0,0,0,128,150,116,4,8,20080103,1,Washington Dulles International,40,Tampa International,1.0,1,1,Southwest Airlines
1,WN,3231,N772SW,7:35:00,7:54:00,19,10:00:00,10:02:00,2,0,0,0,0,0,0,128,145,113,5,10,20080103,1,Washington Dulles International,40,Tampa International,2.0,1,1,Southwest Airlines
2,WN,448,N428WN,6:20:00,6:28:00,8,7:50:00,8:04:00,14,0,0,0,0,0,0,96,90,76,3,17,20080103,2,Indianapolis International,53,Baltimore/Washington International,3.0,2,1,Southwest Airlines
3,WN,3920,N464WN,17:55:00,18:29:00,34,19:25:00,19:59:00,34,2,0,0,0,32,34,90,90,77,3,10,20080103,2,Indianapolis International,53,Baltimore/Washington International,4.0,2,1,Southwest Airlines
4,WN,378,N726SW,19:15:00,19:40:00,25,21:10:00,21:21:00,11,0,0,0,0,0,0,101,115,87,4,10,20080103,2,Indianapolis International,5,Jacksonville International,5.0,3,1,Southwest Airlines
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,AA,1865,N578AA,19:15:00,19:27:00,12,20:20:00,20:44:00,24,12,0,12,0,0,24,197,185,179,3,15,20080612,94,Dallas/Fort Worth International,52,Hollywood Burbank,3949.0,4069,16,American Airlines
1048571,AA,1865,N465AA,19:15:00,19:51:00,36,20:20:00,21:01:00,41,1,0,5,0,35,41,190,185,176,4,10,20080613,94,Dallas/Fort Worth International,52,Hollywood Burbank,3905.0,4069,16,American Airlines
1048572,AA,1865,N207AA,19:15:00,19:52:00,37,20:20:00,21:06:00,46,0,0,9,0,37,46,194,185,166,4,24,20080614,94,Dallas/Fort Worth International,52,Hollywood Burbank,4144.0,4069,16,American Airlines
1048573,AA,1865,N455AA,19:15:00,20:38:00,83,20:20:00,22:15:00,115,7,0,32,0,76,115,217,185,173,3,41,20080615,94,Dallas/Fort Worth International,52,Hollywood Burbank,4110.0,4069,16,American Airlines
1048574,AA,1865,N514AA,19:15:00,20:48:00,93,20:20:00,21:57:00,97,0,93,4,0,0,97,189,185,166,4,19,20080617,94,Dallas/Fort Worth International,52,Hollywood Burbank,3956.0,4069,16,American Airlines

In [89]:
df=df.drop(columns=['CarrierName','UniqueCarrier'])
df

,FlightNum,TailNum,Scheduled_DepTime,Actual_DepTime,Departure_Delay,Scheduled_ArrTime,Actual_ArrTime,Arrival_Delay,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Delay_sum,ActualElapsedTime,Expected_ElapsedTime,AirTime,TaxiIn,TaxiOut,DateKey,airport_FK_x,Airport Name_x,airport_FK_y,Airport Name_y,Aircraft_FK,route_FK,CarrierKey
0,335,N712SW,19:55:00,20:03:00,8,22:25:00,22:11:00,-14,0,0,0,0,0,0,128,150,116,4,8,20080103,1,Washington Dulles International,40,Tampa International,1.0,1,1
1,3231,N772SW,7:35:00,7:54:00,19,10:00:00,10:02:00,2,0,0,0,0,0,0,128,145,113,5,10,20080103,1,Washington Dulles International,40,Tampa International,2.0,1,1
2,448,N428WN,6:20:00,6:28:00,8,7:50:00,8:04:00,14,0,0,0,0,0,0,96,90,76,3,17,20080103,2,Indianapolis International,53,Baltimore/Washington International,3.0,2,1
3,3920,N464WN,17:55:00,18:29:00,34,19:25:00,19:59:00,34,2,0,0,0,32,34,90,90,77,3,10,20080103,2,Indianapolis International,53,Baltimore/Washington International,4.0,2,1
4,378,N726SW,19:15:00,19:40:00,25,21:10:00,21:21:00,11,0,0,0,0,0,0,101,115,87,4,10,20080103,2,Indianapolis International,5,Jacksonville International,5.0,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,1865,N578AA,19:15:00,19:27:00,12,20:20:00,20:44:00,24,12,0,12,0,0,24,197,185,179,3,15,20080612,94,Dallas/Fort Worth International,52,Hollywood Burbank,3949.0,4069,16
1048571,1865,N465AA,19:15:00,19:51:00,36,20:20:00,21:01:00,41,1,0,5,0,35,41,190,185,176,4,10,20080613,94,Dallas/Fort Worth International,52,Hollywood Burbank,3905.0,4069,16
1048572,1865,N207AA,19:15:00,19:52:00,37,20:20:00,21:06:00,46,0,0,9,0,37,46,194,185,166,4,24,20080614,94,Dallas/Fort Worth International,52,Hollywood Burbank,4144.0,4069,16
1048573,1865,N455AA,19:15:00,20:38:00,83,20:20:00,22:15:00,115,7,0,32,0,76,115,217,185,173,3,41,20080615,94,Dallas/Fort Worth International,52,Hollywood Burbank,4110.0,4069,16
1048574,1865,N514AA,19:15:00,20:48:00,93,20:20:00,21:57:00,97,0,93,4,0,0,97,189,185,166,4,19,20080617,94,Dallas/Fort Worth International,52,Hollywood Burbank,3956.0,4069,16

In [90]:
df.to_csv('Fact_table.csv')

In [4]:
def create_date_dimension(start_date, end_date):
    # 1. توليد سلسلة من التواريخ بين البداية والنهاية
    dates = pd.date_range(start=start_date, end=end_date)
    
    # 2. إنشاء DataFrame
    df = pd.DataFrame(dates, columns=['FullDate'])
    
    # 3. استخراج السمات المختلفة (Attributes)
    df['DateKey'] = df['FullDate'].dt.strftime('%Y%m%d').astype(int) # مفتاح فريد بصيغة رقمية
    df['Year'] = df['FullDate'].dt.year
    df['Month'] = df['FullDate'].dt.month
    df['Day'] = df['FullDate'].dt.day
    df['Quarter'] = df['FullDate'].dt.quarter
    df['DayName'] = df['FullDate'].dt.day_name()
    df['MonthName'] = df['FullDate'].dt.month_name()
    df['DayOfWeek'] = df['FullDate'].dt.dayofweek # 0=Monday, 6=Sunday
    df['IsWeekend'] = df['DayOfWeek'].apply(lambda x: 1 if x >= 5 else 0)
    df['WeekOfYear'] = df['FullDate'].dt.isocalendar().week
    
    return df

# مثال للاستخدام: تغطية سنة 2008 (بناءً على بياناتك)
dim_date = create_date_dimension('2008-01-01', '2008-12-31')

# عرض أول 5 صفوف
print(dim_date.head())

# حفظ الملف لاستخدامه في SQL Server أو Power BI
dim_date.to_csv('Dim_Date.csv', index=False)

    FullDate   DateKey  Year  Month  Day  Quarter    DayName MonthName  \
0 2008-01-01  20080101  2008      1    1        1    Tuesday   January
1 2008-01-02  20080102  2008      1    2        1  Wednesday   January
2 2008-01-03  20080103  2008      1    3        1   Thursday   January
3 2008-01-04  20080104  2008      1    4        1     Friday   January
4 2008-01-05  20080105  2008      1    5        1   Saturday   January

   DayOfWeek  IsWeekend  WeekOfYear
0          1          0           1
1          2          0           1
2          3          0           1
3          4          0           1
4          5          1           1

In [2]:
df['Date'].min()

'1/1/2008'

In [3]:
df['Date'].max()

'6/9/2008'

In [ ]:
df['TailNum'].to_csv('Dim_Aircraft.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 28 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Date                  1048575 non-null  object
 1   year                  1048575 non-null  int64
 2   month                 1048575 non-null  int64
 3   day                   1048575 non-null  int64
 4   DayOfWeek             1048575 non-null  int64
 5   UniqueCarrier         1048575 non-null  object
 6   FlightNum             1048575 non-null  int64
 7   TailNum               1048575 non-null  object
 8   Origin                1048575 non-null  object
 9   Dest                  1048575 non-null  object
 10  Distance              1048575 non-null  int64
 11  Scheduled_DepTime     1048575 non-null  object
 12  Actual_DepTime        1048575 non-null  object
 13  Departure_Delay       1048575 non-null  int64
 14  Scheduled_ArrTime     1048575 non-null  object
 15  Actual_ArrTime        1048575 non-null  object
 16  Arrival_Delay         1048575 non-null  int64
 17  CarrierDelay          1048575 non-null  int64
 18  WeatherDelay          1048575 non-null  int64
 19  NASDelay              1048575 non-null  int64
 20  SecurityDelay         1048575 non-null  int64
 21  LateAircraftDelay     1048575 non-null  int64
 22  Delay_sum             1048575 non-null  int64
 23  ActualElapsedTime     1048575 non-null  int64
 24  Expected_ElapsedTime  1048575 non-null  int64
 25  AirTime               1048575 non-null  int64
 26  TaxiIn                1048575 non-null  int64
 27  TaxiOut               1048575 non-null  int64
dtypes: int64(19), object(9)
memory usage: 224.0+ MB

In [9]:
Aircraft=df['TailNum']

In [10]:
Aircraft.drop_duplicates(inplace=True)

In [ ]:
Aircraft.value_counts()

TailNum
N712SW    1
N772SW    1
N428WN    1
N464WN    1
N726SW    1
         ..
N270      1
N924WN    1
N226UA    1
N961UW    1
N348AT    1
Name: count, Length: 5042, dtype: int64

In [12]:
Aircraft.to_csv('Dim_Aircraft',index=False)

In [ ]:
df['Origin'].to_csv('Dim_Airport.csv')

In [1]:

import pandas as pd 
airport=pd.read_csv('Dim_Airport.csv')
airport

         Unnamed: 0 Origin
0                 0    IAD
1                 1    IAD
2                 2    IND
3                 3    IND
4                 4    IND
...             ...    ...
1048570     1048570    DFW
1048571     1048571    DFW
1048572     1048572    DFW
1048573     1048573    DFW
1048574     1048574    DFW

[1048575 rows x 2 columns]

In [2]:
del airport['Unnamed: 0']

In [3]:
airport.drop_duplicates(inplace=True)

In [4]:
airport

        Origin
0          IAD
2          IND
12         ISP
32         JAN
37         JAX
...        ...
811053     LWB
866377     ACK
945139     WYS
1028434    BJI
1030116    INL

[296 rows x 1 columns]

In [7]:
airport.rename({'Origin':'Airport_Code'},axis='columns',inplace=True)

In [ ]:
# 
airport.drop_duplicates

Origin  Airport_Code
0                IAD
2                IND
12               ISP
32               JAN
37               JAX
...              ...
811053           LWB
866377           ACK
945139           WYS
1028434          BJI
1030116          INL

[296 rows x 1 columns]

In [1]:
import pandas as pd

airport=pd.read_csv('Dim_Airport.csv')
airport

    Airport_Code
0            IAD
1            IND
2            ISP
3            JAN
4            JAX
..           ...
291          LWB
292          ACK
293          WYS
294          BJI
295          INL

[296 rows x 1 columns]

In [ ]:
airport['Airport_Code'].unique()

array(['IAD', 'IND', 'ISP', 'JAN', 'JAX', 'LAS', 'LAX', 'LBB', 'LIT',
       'MAF', 'MCI', 'MCO', 'MDW', 'MHT', 'MSY', 'OAK', 'OKC', 'OMA',
       'ONT', 'ORF', 'PBI', 'PDX', 'PHL', 'PHX', 'PIT', 'PVD', 'RDU',
       'RNO', 'RSW', 'SAN', 'SAT', 'SDF', 'SEA', 'SFO', 'SJC', 'SLC',
       'SMF', 'SNA', 'STL', 'TPA', 'TUL', 'TUS', 'ABQ', 'ALB', 'AMA',
       'AUS', 'BDL', 'BHM', 'BNA', 'BOI', 'BUF', 'BUR', 'BWI', 'CLE',
       'CMH', 'CRP', 'DAL', 'DEN', 'DTW', 'ELP', 'FLL', 'GEG', 'HOU',
       'HRL', 'ROC', 'ORD', 'EWR', 'SYR', 'IAH', 'CRW', 'FAT', 'COS',
       'MRY', 'LGB', 'BFL', 'EUG', 'ICT', 'MEM', 'BTV', 'MKE', 'LFT',
       'BRO', 'PWM', 'MSP', 'SRQ', 'CLT', 'CVG', 'GSO', 'SHV', 'DCA',
       'TYS', 'GSP', 'RIC', 'DFW', 'BGR', 'DAY', 'GRR', 'CHS', 'CAE',
       'TLH', 'XNA', 'GPT', 'VPS', 'LGA', 'ATL', 'MSN', 'SAV', 'BTR',
       'LEX', 'LRD', 'MOB', 'MTJ', 'GRK', 'AEX', 'PNS', 'ABE', 'HSV',
       'CHA', 'MFE', 'MLU', 'DSM', 'MGM', 'AVL', 'LCH', 'BOS', 'MYR',
       'CLL', 'DAB', 'ASE', 'ATW', 'BMI', 'CAK', 'CID', 'CPR', 'EGE',
       'FLG', 'FSD', 'FWA', 'GJT', 'GRB', 'HNL', 'KOA', 'LAN', 'LIH',
       'MBS', 'MDT', 'MFR', 'OGG', 'PSP', 'RAP', 'ROA', 'SBA', 'SBN',
       'SPI', 'TEX', 'YUM', 'AVP', 'CWA', 'DRO', 'ILM', 'ITO', 'JFK',
       'TVC', 'HDN', 'SBP', 'CLD', 'HPN', 'MIA', 'SGF', 'TRI', 'SUN',
       'SGU', 'SLE', 'MSO', 'BZN', 'YKM', 'GTF', 'BIL', 'JAC', 'MOD',
       'FAR', 'GUC', 'AZO', 'PIA', 'MLI', 'LNK', 'FCA', 'IDA', 'BIS',
       'PSC', 'COD', 'TWF', 'RDM', 'HLN', 'RDD', 'PIH', 'EKO', 'LWS',
       'SMX', 'ACV', 'OXR', 'CEC', 'CIC', 'PMD', 'RFD', 'BTM', 'IYK',
       'IPL', 'BLI', 'CDC', 'SJU', 'STT', 'ANC', 'STX', 'MLB', 'PHF',
       'PFN', 'FAY', 'AGS', 'GNV', 'ABY', 'DHN', 'EVV', 'FNT', 'OAJ',
       'TOL', 'SWF', 'EWN', 'MEI', 'GTR', 'LYH', 'HHH', 'EYW', 'VLD',
       'CSG', 'ACY', 'FSM', 'MCN', 'CHO', 'FLO', 'BQK', 'SCE', 'TUP',
       'TYR', 'LAW', 'SPS', 'ABI', 'GGG', 'ACT', 'SJT', 'TXK', 'CMI',
       'ROW', 'RST', 'MQT', 'LSE', 'DBQ', 'GFK', 'MOT', 'DLH', 'SUX',
       'PLN', 'BGM', 'ERI', 'ALO', 'CMX', 'RHI', 'ELM', 'JNU', 'KTN',
       'SIT', 'PSG', 'CDV', 'YAK', 'BRW', 'OME', 'OTZ', 'BET', 'FAI',
       'SCC', 'ADQ', 'WRG', 'ADK', 'PSE', 'BQN', 'BPT', 'RKS', 'GCC',
       'MKG', 'DLG', 'AKN', 'LWB', 'ACK', 'WYS', 'BJI', 'INL'],
      dtype=object)

In [ ]:
route=df[['Origin','Dest','Distance']]
route.shape

        Origin Dest  Distance
0          IAD  TPA       810
1          IAD  TPA       810
2          IND  BWI       515
3          IND  BWI       515
4          IND  JAX       688
...        ...  ...       ...
1048570    DFW  BUR      1231
1048571    DFW  BUR      1231
1048572    DFW  BUR      1231
1048573    DFW  BUR      1231
1048574    DFW  BUR      1231

[1048575 rows x 3 columns]

In [16]:
route.drop_duplicates(inplace=True)
route.shape

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_10124\2797004421.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  route.drop_duplicates(inplace=True)

(5005, 3)

In [ ]:
route['route_FK']=range(1,len(route)+1)
route

        Origin Dest  Distance  route_FK
0          IAD  TPA       810         1
2          IND  BWI       515         2
4          IND  JAX       688         3
5          IND  LAS      1591         4
6          IND  MCO       828         5
...        ...  ...       ...       ...
1030522    MSP  BJI       199      5001
1030927    MEM  COS       855      5002
1030993    COS  MEM       855      5003
1032242    BDL  MEM      1048      5004
1032321    MEM  BDL      1048      5005

[5005 rows x 4 columns]

In [19]:
route.to_csv('Dim_Route.csv',index=False)

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('Dim_Airport.csv')
df

,Code,Airport Name,City
0,IAD,Washington Dulles International,"Washington, D.C. / Dulles"
1,IND,Indianapolis International,"Indianapolis, IN"
2,ISP,Long Island MacArthur,"Islip, NY"
3,JAN,Jackson–Medgar Wiley Evers International,"Jackson, MS"
4,JAX,Jacksonville International,"Jacksonville, FL"
...,...,...,...
293,WYS,Yellowstone,"West Yellowstone, MT"
294,BJI,Bemidji Regional,"Bemidji, MN"
295,INL,Falls International,"International Falls, MN"
296,Sources,NaN,NaN
297,http://mars.gmu.edu/jspui/bitstream/handle/192...,NaN,NaN

In [4]:
df['airport_FK']=range(1,len(df)+1)

In [6]:
df.to_csv('Dim_Airport.csv',index=False)